### PR TITLE
Fix button text visibility

### PR DESCRIPTION
**Pull request by KrishnaIyer**
#### Summary

Fix button text visibility

#### Screenshots

Screen Shot 2024-01-05 at 14 16 29

#### Changes

- Make button text visible.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Comment by johanstokking** [comment]
How about setting `color` for `is-primary`?

**Review by nejraselimovic — APPROVED** [review]

**Review by adriansmares — COMMENTED** [review]
Bumping this PR here as the bug is still present but we didn't merge this. I don't have a strong opinion here, so I defer to @johanstokking's review.

**Comment by KrishnaIyer** [comment]
@pierrephz: Can you advise what we can do with these links?

**Comment by KrishnaIyer** [comment]
replaced by https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1352

**Pull request closed without merging**
