### PR TITLE
Add enterprise + open source CLI download link builder

### LINKED ISSUE #696: Document instructions for downloading `tti-lw-cli`(Enterprise CLI) binaries
#### Summary
The Things Stack CLI can be installed using a package manager on Mac and Linux operating systems. If the User's operating system doesn't support package managers, then they need to rely on binaries.

Currently, the CLI binaries are available for *ttn-lw-cli* but not for *tti-lw-cli*.
#### Why do we need this ?
Enterprise users can download binaries if the package managers aren't supported in their operating systems.
#### What is already there? What do you see now?
- Instructions on how to download the `ttn-lw-cli` and `tti-lw-cli` via the package manager.
- Also, we have instructions on how to download the binaries for `ttn-lw-cli`.

Ref: https://www.thethingsindustries.com/docs/getting-started/cli/installing-cli/
#### What is missing? What do you want to see?
Instructions on how to download `tti-lw-cli` binaries for Enterprise users.
#### How do you propose to document this?
...
#### Can you do this yourself and submit a Pull Request?
No

### PR DESCRIPTION
**Pull request by benolayinka**
#### Summary

Closes #696 

Please double check the links

#### Screenshots

Bildschirmfoto 2022-01-11 um 19 50 49

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [x] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Review by htdvisser — APPROVED** [review]
I made some small changes to the JS. Good to go now.

**Comment by benolayinka** [comment]
> I made some small changes to the JS. Good to go now.

thanks. what needed to be fixed?

**Comment by htdvisser** [comment]
Nothings serious, mostly some formatting. 
And I removed the `dict`s that you used for populating the selects, because those resulted in non-deterministic ordering of the options.

**Review by nejraselimovic — APPROVED** [review]
Pretty cool, links look fine to me. Btw I think we can remove that text below the Download button

**Comment by benolayinka** [comment]
> Nothings serious, mostly some formatting.
> And I removed the `dict`s that you used for populating the selects, because those resulted in non-deterministic ordering of the options.

awesome, thank you.

> Pretty cool, links look fine to me. Btw I think we can remove that text below the Download button

i'm going to leave this just to allow people to double check their downloads. i know the ui is not great but it's better than nothing.

**Pull request merged**
