### PR TITLE
Remove references to customizable email templates

### PR DESCRIPTION
**Pull request by htdvisser**
#### Summary

This marks email template customization as "removed" and adds the `dir` email provider.

Refs https://github.com/TheThingsNetwork/lorawan-stack/pull/5406

#### Screenshots

n/a

#### Changes

- Fixed `removed-in-version` shortcode
- Removed email template stuff
- Added `dir` email provider

#### Notes for Reviewers

~Not sure what our current practice is for deleting pages. If instead of deleting pages, we want to update them with a message, then I can do that too.~

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Comment by htdvisser** [comment]
> Not sure what our current practice is for deleting pages. If instead of deleting pages, we want to update them with a message, then I can do that too.

@nejraselimovic @benolayinka what about this?

**Comment by nejraselimovic** [comment]
> > Not sure what our current practice is for deleting pages. If instead of deleting pages, we want to update them with a message, then I can do that too.
> 
> @nejraselimovic @benolayinka what about this?

I see that this feature has been barely used, but still, I think the best option is to add a warning message for now, and I can completely delete those pages later

**Comment by htdvisser** [comment]
Updated accordingly, @nejraselimovic

**Review by nejraselimovic — APPROVED** [review]
Great!

**Pull request merged**
