### PR TITLE
doc: Fix interop documentation

### PR DESCRIPTION
**Pull request by michalborkowski96**
#### Summary
Fix an oversight in the documentation

#### Changes
Documented value was wrong

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
We use `${NetworkName}/${Environment}/${Cluster}` everywhere, right? Isn't the template wrong?

**Comment by michalborkowski96** [comment]
Unfortunately sometimes we use one, and sometimes the other one.

https://github.com/TheThingsIndustries/lorawan-stack-aws/blob/341dba63b253bcca55e732c1c3f65252ac8155d6/deploy/src/5-1-ecs-cluster.py#L459

**Comment by johanstokking** [comment]
> Unfortunately sometimes we use one, and sometimes the other one.

Where?

> https://github.com/TheThingsIndustries/lorawan-stack-aws/blob/341dba63b253bcca55e732c1c3f65252ac8155d6/deploy/src/5-1-ecs-cluster.py#L459

This is a DNS name, not a CFT export/import.

**Comment by michalborkowski96** [comment]
> This is a DNS name, not a CFT export/import.

And so is this piece of documentation about.

**Review by johanstokking — APPROVED** [review]
🤦‍♂️

**Pull request merged**
