### PR TITLE
doc: Update device import doc

### LINKED ISSUE #535: Update device import documentation
#### Summary
Following up on https://github.com/TheThingsNetwork/lorawan-stack/pull/4531

#### Why do we need this ?
The flow has been updated, so we need to update the text and screenshots accordingly

#### Can you do this yourself and submit a Pull Request?
Yes

### PR DESCRIPTION
**Pull request by nejraselimovic**
#### Summary
Closes #535 

#### Notes for Reviewers
Not sure what "Targeted components" checkboxes represent, waiting for input

#### Checklist
- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Review by benolayinka — APPROVED** [review]

**Comment by adriansmares** [comment]
> Not sure what "Targeted components" checkboxes represent, waiting for input

They refer to the components in which the end device is going to be created. In TTS when you create a device you actually create it in 4 places (IS/NS/AS/JS), and that option allows you to specify if the imported devices should be added in all of the registries.

**Comment by nejraselimovic** [comment]
> > Not sure what "Targeted components" checkboxes represent, waiting for input
> 
> They refer to the components in which the end device is going to be created. In TTS when you create a device you actually create it in 4 places (IS/NS/AS/JS), and that option allows you to specify if the imported devices should be added in all of the registries.

As an average user, I have no idea what that means for me. What would happen if I uncheck some boxes, i.e. if my device is not added to all registries? Is there a best practice for this, to check all these boxes or something?

**Comment by adriansmares** [comment]
I've asked around on why we have these in the first place. They have been added in https://github.com/TheThingsNetwork/lorawan-stack/pull/1480 . 

I think that the original use case was that manufacturers could mass import the devices as IS + JS in the Global Join Server, and then users can just use the Global Join Server when they attempt to register their devices.

**Review by adriansmares — APPROVED** [review]

**Comment by benolayinka** [comment]
@nejraselimovic I think you can go ahead and merge this. Make an issue to follow up about target components.

**Pull request merged**
