### PR TITLE
Reorganize docs

### PR DESCRIPTION
**Pull request by benolayinka**
#### Summary

Reorganizational changes suggested by Nejra for improving docs readability.

#### Changes

See commits

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Review by johanstokking — COMMENTED** [review]
Isn't this breaking external links? Should we have redirects?

**Comment by nejraselimovic** [comment]
> Isn't this breaking external links? Should we have redirects?

@johanstokking Sorry but I'm not really sure what you mean by this, can you explain me the issue?

@benolayinka I've fixed some broken references and pushed some small changes, please check them out

**Comment by johanstokking** [comment]
> @johanstokking Sorry but I'm not really sure what you mean by this, can you explain me the issue?

That if we have documentation links that currently work, i.e. https://thethingsstack.io/getting-started/aws/ami/post-deployment/, that these links still work.

If you reorganize docs, these links may break. So links pasted on the forums or sent before to customers may not work anymore.

**Comment by nejraselimovic** [comment]
> > @johanstokking Sorry but I'm not really sure what you mean by this, can you explain me the issue?
> 
> That if we have documentation links that currently work, i.e. https://thethingsstack.io/getting-started/aws/ami/post-deployment/, that these links still work.
> 
> If you reorganize docs, these links may break. So links pasted on the forums or sent before to customers may not work anymore.
> 
> For example, https://thethingsstack.io/getting-started/migrating-from-v2 will break when we merge this. You should use [aliases](https://gohugo.io/content-management/urls/#aliases) to keep the current URLs working.

Ok, I get it now. I can work on this

**Comment by benolayinka** [comment]
> > > @johanstokking Sorry but I'm not really sure what you mean by this, can you explain me the issue?
> > 
> > 
> > That if we have documentation links that currently work, i.e. https://thethingsstack.io/getting-started/aws/ami/post-deployment/, that these links still work.
> > If you reorganize docs, these links may break. So links pasted on the forums or sent before to customers may not work anymore.
> > For example, https://thethingsstack.io/getting-started/migrating-from-v2 will break when we merge this. You should use [aliases](https://gohugo.io/content-management/urls/#aliases) to keep the current URLs working.
> 
> Ok, I get it now. I can work on this

You rock, thanks for doing this 🙌🏽

**Review by johanstokking — APPROVED** [review]
Great!

**Review by kschiffer — APPROVED** [review]
Codeowned file LGTM

**Review by neoaggelos — APPROVED** [review]

**Pull request merged**
