### PR TITLE
doc: Add information about OAuth client creation

### LINKED ISSUE #439: Add information about OAuth client Registration
#### Summary

The current version of the documentation contains a statement that we need an OAuth client registration, but it does't contain information, how we can do this.

#### Why do we need this ?

To simplify OAuth client registration.

#### What is already there? What do you see now?

https://www.thethingsindustries.com/docs/reference/api/authentication/#oauth-access-tokens

#### What is missing? What do you want to see?

Add CLI command for creation of the OAuth client

#### How do you propose to document this?

Add CLI command for creation of the OAuth client

#### Can you do this yourself and submit a Pull Request?

Yes

### PR DESCRIPTION
**Pull request by romach**
#### Summary

Adds information about OAuth client creation.

Closes #439

#### Screenshots

...

#### Changes

Added TTN CLI command for creating an OAuth client.

#### Notes for Reviewers

...

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Review by htdvisser — COMMENTED** [review]
Considering how many OAuth client requests we received for the exact copy-paste of the example in V2, I don't think it's a good idea to add the example at this point.

Instead I think we should wait for the Console to support requesting (and managing) OAuth clients (https://github.com/TheThingsNetwork/lorawan-stack/issues/4300)

**Comment by nejraselimovic** [comment]
@htdvisser since https://github.com/TheThingsNetwork/lorawan-stack/issues/4300 has been completed, I guess this isn't blocked anymore. Should we merge this? Also document managing OAuth clients in the Console?

**Comment by NicolasMrad** [comment]
any updates on this?

**Comment by nejraselimovic** [comment]
> Should we document this with Console screenshots instead then? And keep the CLI example?

We need to do both Console and CLI, with those "CLI" and "Console" tabs to switch between them. I can take care of the Console part, I just have one question. In this PR, when creating an OAuth client using CLI, there is this flag `--organization-id` and `--user-id`, but I don't see such settings when creating an OAuth client using Console. Why is that?

**Pull request merged**
