### PR TITLE
Improve image display in docs

### PR DESCRIPTION
**Pull request by kschiffer**
#### Summary
This PR introduces some improvements for how images are displayed in the docs.

image
image
image

#### Changes
- Limit the height of `<figure />` to `500px`, e.g. to avoid gigantic mobile screenshots
- Add a `float` class to figures to enable floating smaller images into the text content
- Add a lightbox feature for `<figure />` (click to enlarge)
- Prettify js code (JsPrettier)

#### Notes for Reviewers
@nejraselimovic so this would be the groundwork for improving the image display. What needs to be done from here is replace any plain images of screenshots (or anything comparable like schematics) with the figure shortcode. That way, the image says will stay convenient regardless of the image dimension. Also, you can take a look at where it makes sense to use the `float` class. I've included an example usage for the Dragino gateway guide.

It would mean that #127 becomes obsolete and replaced with this PR after you added the replacements to `<figure />` into this PR.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`
- [x] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Comment by kschiffer** [comment]
An updated guideline for how to use images inside the doc content could look like this:

*   Any image that is essential to following the guide, such as screenshots, schematics, etc, should use the plain figure shortcode.
*   The figure will take up the whole space and allow to be viewed in full, when clicked
*   Any complimentary image that is not essential to following the guide, such as e.g. images of devices, can use the `float` class, so that it embeds into the content and does not break the reading flow
*   If the image is a cut-out, the `plain`\-class can be used to render the figure without border (this class still needs to be added)
*   Plain images (`title`) should be avoided but can be necessary to achieve special stylings

The reason to avoid plain images is that 1) using the figure idiom is more semantic and 2) it's not (really) possible to add a class to the plain image markdown syntax, to have more control over how it is displayed.

**Review by pierrephz — APPROVED** [review]

**Comment by nejraselimovic** [comment]
I added a `plain` class to remove shadow where necessary and implemented these changes across the whole Gateways section. I think the figures with the `float` class are good, although we will need to watch out when positioning them.

@kschiffer @benolayinka please check if this is the final way to go before I continue with implementing across the whole documentation

**Comment by kschiffer** [comment]
> I added a `plain` class to remove shadow where necessary

Will add this.

> I think the figures with the `float` class are good, although we will need to watch out when positioning them.

Indeed, this is definitely not a set-it-forget-it thing but needs to be verified on the rendered page.

> please check if this is the final way to go before I continue with implementing across the whole documentation

Will do.

**Comment by kschiffer** [comment]
I've added the `plain` style. And checked through some pages and it looks good to me like this.

Should we consider this now a replacement of #126 ?

**Comment by benolayinka** [comment]
Looks good. I would prefer to use Hugo's render-image hook to generate our own html but it doesn't look like it supports a `class` parameter

https://gohugo.io/getting-started/configuration-markup/#markdown-render-hooks
https://discourse.gohugo.io/t/simple-image-render-hook-template-for-responsive-images/22464

**Comment by kschiffer** [comment]
Yeah, exactly. We really need to flexibly modify the appearance though.

**Review by benolayinka — APPROVED** [review]
This looks great. Thanks @nejraselimovic and @kschiffer 

Screenshot 2020-12-08 at 12 30 46

**Comment by nejraselimovic** [comment]
> I've added the `plain` style and also fixed a javascript error. I checked through some pages and it looks good to me like this.
> 
> Should we consider this now a replacement of #126 ?

Yes, #126 is closed and I'm merging this. I'll leave updating of all image instances for another PR.

**Review by nejraselimovic — APPROVED** [review]

**Pull request merged**
