### PR TITLE
doc: Add AWS IP note

### PR DESCRIPTION
**Pull request by benolayinka**
#### Summary

Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/406#issuecomment-880390048

#### Screenshots

Bildschirmfoto 2021-07-19 um 15 44 04

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Comment by michalborkowski96** [comment]
Well, actually our IP addresses are static (we have Elastic IPs), but from customer's point of view they should assume we can have any address that AWS can have.

@htdvisser maybe I should add a note about Elastic IPs? So that people who deploy the stack on AWS ECS themselves know what addresses to whitelist, instead of everything related to AWS, which might be important to them from security perspective.

**Review by htdvisser — COMMENTED** [review]
Mostly LGTM.

Maybe we can indeed also clarify this a bit in the documentation for the AWS ECS deployment model.

Generally speaking, our AWS ECS deployments (inlcuding TTS Community Edition and TTS Cloud) have two IPv4 addresses for incoming traffic (to the load balancer) and two IPv4 addresses for outgoing traffic (from the NAT gateway). These addresses will _usually_ not change, so in our AWS ECS deployment guide we can definitely tell operators how to find them (we should probably just export them from the VPC CloudFormation stack like we already do with the EIPs of the load balancer).

For The Things Stack Cloud I'm not quite sure what we should do. Generally these IPs will stay the same, but in case we ever have to recover from a disaster (like we had to do with our TTN V2 EU cluster) it's not impossible that the addresses change.

As far as I know, full IPv6 support on the AWS deployments is still work in progress (@michalborkowski96?). Those addresses will most definitely not be static, but I think they'll all be in the CIDR that's associated with the VPC.

So if it's really important for users to know the IP addresses of the NAT gateways in ECS deployments, we could perhaps publish the IPv4 addresses as well as the IPv6 CIDR in a DNS TXT record, and keep that up-to-date if it ever changes?

**Comment by benolayinka** [comment]
AWS Marketplace Launcher users can find their IP addresses if they need to whitelist them. This issue was for Cloud users

**Comment by michalborkowski96** [comment]
@htdvisser I do not think that we'll remember to update the documentation. Especially after we have a disaster recovery.

**Comment by benolayinka** [comment]
I'm also all for exposing the IPs for AWS Launcher in CloudFormation as a separate PR.

For now, I'd like to merge this just so Cloud customers know that Cloud runs on AWS with this range of potential addresses, which is guaranteed to be true forever. If customers need an actual IP, that is a support question we can answer individually, I think it's going to be very rare.

**Review by michalborkowski96 — APPROVED** [review]

**Pull request merged**
