### PR TITLE
Update register-devices.md

### PR DESCRIPTION
**Pull request by jpmeijers**
ttn-lw-cli complains with a warning message when the example device create command from this document is used:
`Flag --app-eui has been deprecated, use the join-eui flag`

This PR changes `--app-eui` to `--join-eui`.

(after writing the comments below) The documentation under https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/tti-join-server/register-devices/ seems outdated and should rather looks like the commands under https://www.thethingsindustries.com/docs/devices/adding-devices/

#### Summary

...

#### Screenshots

...

#### Changes

- ...
- ...

#### Notes for Reviewers

...

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Comment by jpmeijers** [comment]
Using this specific command from the docs does not set the Network Layer parameters:
image

The assumption is that the default settings should be used. Is what I see correct, or do we need to add more flags to this device create command?

**Comment by jpmeijers** [comment]
From https://clavisound.no-ip.info/minisites/ttn/docs/ttnv3.cli.php I see a better example command that does fill in the Network layer settings. I needed 3 more flags:

```
  --frequency-plan-id EU_863_870_TTN \
  --lorawan-version 1.0.2 \
  --lorawan-phy-version 1.0.2-b \
```

**Comment by michalborkowski96** [comment]
@adriansmares I think you'd be the most suitable person to take this

**Review by adriansmares — APPROVED** [review]
Thanks for the PR !

Regarding the question: there is a `--defaults` which will automatically set the server addresses, but MAC related parameters such as the frequency plan ID and versions need to explicitly get filled in.

https://github.com/TheThingsNetwork/lorawan-stack/blob/e572f4cbd3a18fd25b28f11149e0ddd0523259a2/cmd/ttn-lw-cli/commands/end_devices.go#L377

**Comment by nejraselimovic** [comment]
@jpmeijers @adriansmares what is the status of this PR? is this ready to merge?

**Comment by adriansmares** [comment]
I will leave the docs as is (since in 1.0.x terms, the JoinEUI is still called an AppEUI) and fix this on the stack side separately.

**Pull request closed without merging**
