### PR TITLE
doc: Add whats-new

### PR DESCRIPTION
**Pull request by benolayinka**
#### Summary

Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/95

Display what's new on homepage and in what's new section

Bildschirmfoto 2021-04-01 um 12 35 44

Bildschirmfoto 2021-04-01 um 12 10 47

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Comment by johanstokking** [comment]
Looks great.

As long as these pages are added manually, please update the release instructions in `lorawan-stack` to include the changelog.

Also, how do we differentiate between open source and proprietary changes? One is a subset of the other.

**Review by nejraselimovic — COMMENTED** [review]
I think the idea is great and really useful, but I wouldn't put this on the main page. I would rather have it only on a separated page, maybe even put it in the `Release Notes` section next to `Reference` or something

**Comment by kschiffer** [comment]
Good idea, but it needs some design love.

@pierrephz can you suggest a styling and positioning of such section?

**Review by kschiffer — COMMENTED** [review]
Good idea, but it needs some design love.

@pierrephz can you suggest a styling and positioning of such section?

**Comment by benolayinka** [comment]
> I think the idea is great and really useful, but I wouldn't put this on the main page. I would rather have it only on a separated page, maybe even put it in the `Release Notes` section next to `Reference` or something

We have to put it somewhere people will see it, its information people should and will be curious about. I don't think we have room in the navbar to create a section for it, and if it's buried somewhere, maybe nobody will find it. Plenty of documentation sites put the release notes on the homepage - it also shows that people are working actively on the product.

Hugo uses a carousel on the front page to share this information -> https://gohugo.io/

**Comment by pierrephz** [comment]
Here is my suggestion for the "what's new" section:

The_Things_Stack_doc_main_page

let's keep this section as tiny as possible.
The user can drag the information horizontally. He can also click on "see details" to go to the dedicated page

Lets me know your thoughts @benolayinka @kschiffer

**Review by pierrephz — CHANGES_REQUESTED** [review]
see my comment

**Comment by kschiffer** [comment]
Nice! Two things:

*   I think it's better to place the section after the hero (with the three visuals)
*   Reword `See details ->` to `See all changes of this release ->`

Also, we might have releases that do not have anything in the "Add section". I think for this reason it's best to cycle through all bullet points (not just of the added section) for this preview.

I think I'd have to jump in to implement this. I'll see what I can do.

**Comment by benolayinka** [comment]
@kschiffer leaving this one to you for now. let me know if you need me for anything.

**Comment by benolayinka** [comment]
Also add instructions for updating what's new to the release template https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/233

**Comment by kschiffer** [comment]
It's finally here:



@benolayinka and @nejraselimovic please double check to avoid self-review. Then we can merge I guess.

**Comment by benolayinka** [comment]
Suhweeet @nejraselimovic can you finish this one? Should just be copy pasting over the changelogs

**Comment by nejraselimovic** [comment]
> Suhweeet @nejraselimovic can you finish this one? Should just be copy pasting over the changelogs

Sure, do you mean all of them or starting from a specific version (you started at 3.10.0) to the most recent one?

Btw, I just noticed this: 

Screenshot from 2021-03-31 11-30-32

I don't know if it's just me, but 3.10.6 shouldn't be at the bottom of this list

**Comment by benolayinka** [comment]
> > Suhweeet @nejraselimovic can you finish this one? Should just be copy pasting over the changelogs
> 
> Sure, do you mean all of them or starting from a specific version (you started at 3.10.0) to the most recent one? Also which repos? I added everything from [here](https://github.com/TheThingsIndustries/lorawan-stack) that's newer than 3.10.6.
> 
> Btw, I just noticed this:
> 
> Screenshot from 2021-03-31 11-30-32
> 
> I don't know if it's just me, but 3.10.6 shouldn't be at the bottom of this list

Yep perfect! You rock

**Comment by benolayinka** [comment]
@johanstokking only thing left is that we aren't marking enterprise only changes. The most straightforward way I can think of is just to include (Enterprise Only) in the changelog when changes are made in the lorawan-stack repo.

**Comment by johanstokking** [comment]
> @johanstokking only thing left is that we aren't marking enterprise only changes. The most straightforward way I can think of is just to include (Enterprise Only) in the changelog when changes are made in the lorawan-stack repo.

I think it would be best if we separate this in `CHANGELOG.md` anyway. This is helpful for ourselves because we get a bunch of merge conflicts.

What we could do is something like:

```
### Added

- Profile settings view to the Account App.
  - Functionality to change basic profile information, such as name, email address and profile picture.
  - Functionality to update the account password.
  - Functionality to delete the account.

### Changed

- Improved logging.

#### Enterprise

- AWS IoT integration is now implemented as package instead of a pub/sub provider.
```

---

There's a bit of a gray area here between Enterprise and Community. The Community runs a limited version of Enterprise. Since the `CHANGELOG.md` is only about the product (driven by devs), we don't differentiate the deployment configuration (which is driven by ops). But let's try to solve that problem later.

@htdvisser ACK on the **Enterprise** sections in the changelog?

**Review by pierrephz — APPROVED** [review]

**Review by adriansmares — APPROVED** [review]
:+1:

**Pull request merged**
