### PR TITLE
doc: Improve ui of the home page

### PR DESCRIPTION
**Pull request by pierrephz**
#### Summary

Home page UI improvements

- Modified the blue color
- Increased width of title and subtitle sections
- Reworked the UI of the `what’s new` section
- Modified the sizing of the schema
- Changes cards UI of the front page

#### What still needs to be done

@benolayinka, the frontend of the `what’s new` section is done, but I haven’t managed to do the backend myself.

By that I mean:
- the data of the current version of the console (1)
- display real datas of the new features in the section (2)
- the real number of new features that have been added (3)

Screenshot 2021-06-09 at 15 14 30

Ben, is it possible for you to use my branch to complete the backend, end push?
If there is any other question, you can message me

#### Notes for Reviewers

I haven't removed the old `what’s new` section (turned it into comment). Would like to have an approval before to remove it for good

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Comment by pierrephz** [comment]
@benolayinka yes, I made it in a way that it just becomes a CTA on a smaller screen, this is already responsive, you don't need to worried about the UI.
Also, the lorem ipsum I used seem to be wider than any other update content we would have

**Comment by benolayinka** [comment]
@pierrephz the fixed three elements also creates a problem when the window gets wide.

Bildschirmfoto 2021-06-16 um 14 46 50

or by allowing flex to assign widths:

Bildschirmfoto 2021-06-16 um 14 48 15

**Comment by benolayinka** [comment]
@pierrephz how about this? i added your styles to @kschiffer flexible design

Bildschirmfoto 2021-06-16 um 15 05 00

Bildschirmfoto 2021-06-16 um 15 05 12

**Comment by pierrephz** [comment]
@benolayinka the main point of reworking the UI was **removing the gradient on the right**, making the user want to scroll horizontally.
So it's fine if you mix our work, but at least can you remove this gradient?

This looks fine to me, maybe you could add one more `<li>` on big screen?

> or by allowing flex to assign widths:
> 
> Bildschirmfoto 2021-06-16 um 14 48 15

### More:

- Small detail to be fixed: the arrow of `See all release notes →` should be `→` and not `->`

- I've set a breakpoint at 800px where this section becomes a CTA, we should keep it as well (see screenshot below):

image

- I did some modifications on the cards: align the buttons at the bottom, added a border, changed the shadow, and the font title (see screenshot below)

image

**Comment by benolayinka** [comment]
@pierrephz because of the layout of the markdown it's not possible to fix the number of elements which are displayed. There is an unknown number of <ul> each with an unknown number of <li>s. @kschiffer's solution is much, much better because it works perfectly regardless of the number of elements.

i hacked it in the example to display only three by displaying one <li> from each of the first three <ul>s, but
- if there are less than three <ul> it will break
- the css is really ugly and it breaks the +n counter

i think that with the +n button there, nobody is going to get confused by the gradient or try to scroll. this is a really small thing on our docs page which is not a critical UI component anyway. i'm going to leave it as is with the gradient and the +n button, because it works and looks consistent.

the rest of your changes (breakpoint, cards) should still be in there. can you do a git pull and take a look to make sure?

**Comment by pierrephz** [comment]
@benolayinka ok let's go like that

**Review by benolayinka — APPROVED** [review]

**Pull request merged**
