### PR TITLE
doc: Release docs v3.13.0

### LINKED ISSUE #359: Release v3.13.0
#### Overview

This is a checklist for releases. This is filled in by both the releaser and the reviewer where necessary.

#### Update Documentation

- [x] Create a new release in the [`whats-new` section](https://github.com/TheThingsIndustries/lorawan-stack-docs/tree/master/doc/content/whats-new) and copy the release CHANGELOG from [TheThingsIndustries/lorawan-stack](https://github.com/TheThingsIndustries/lorawan-stack). The title is the release version and the date is the release date.
- [x] Update the [documentation version](https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/doc/config/_default/config.toml#L28) to match the current minor, if necessary (`v3.${minor}`).
- [x] To generate documentation, create a clone of [TheThingsIndustries/lorawan-stack](https://github.com/TheThingsIndustries/lorawan-stack), and **checkout the git tag of the release**.
- [x] To generate API documentation, run the following from within the clone of [TheThingsIndustries/lorawan-stack](https://github.com/TheThingsIndustries/lorawan-stack): 

```bash
$ tools/bin/mage ttiProto:hugoData
```

- [x] Copy generated files to `lorawan-stack-docs` with the following command:

```bash
$ cp api/ttn.lorawan.v3/*.yml /path/to/lorawan-stack-docs/doc/data/api/ttn.lorawan.v3/
$ cp api/tti.lorawan.v3/*.yml /path/to/lorawan-stack-docs/doc/data/api/tti.lorawan.v3/
```

- [x] To generate and export CLI documentation from within the clone of [TheThingsIndustries/lorawan-stack](https://github.com/TheThingsIndustries/lorawan-stack), first run the following command to build the CLI:

```bash
$ go build -tags tti ./cmd/tti-lw-cli
```

- [x] Then export the CLI documentation using the following command:

```bash
$ HOME='$HOME' ./tti-lw-cli gen-yaml-doc -o /path/to/lorawan-stack-docs/doc/data/
```

#### Check (for reviewers)

- [ ] A new section has been created in [`whats-new`](doc/content/whats-new) with the corresponding CHANGELOG from [TheThingsIndustries/lorawan-stack](https://github.com/TheThingsIndustries/lorawan-stack). The title is the release version and the date is the release date.
- [ ] The documentation version is up to date.
- [ ] The TTI and TTN API documentation has been generated and updated in [doc/data/api](https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/doc/data/api). This includes the following files:

```
doc/data/api/tti.lorawan.v3/messages.yml
doc/data/api/tti.lorawan.v3/services.yml
doc/data/api/tti.lorawan.v3/enums.yml
doc/data/api/ttn.lorawan.v3/messages.yml
doc/data/api/ttn.lorawan.v3/services.yml
doc/data/api/ttn.lorawan.v3/enums.yml
```

- [ ] The TTI CLI documentation has been generated and updated in [doc/data](https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/doc/data). This includes the following file:

```
doc/data/ttn-lw-cli.yml
```

- [ ] All generated documentation matches the version that is being released.

### PR DESCRIPTION
**Pull request by nejraselimovic**
#### Summary
Closes #359 

#### Check (for reviewers)
- [x] A new section has been created in [`whats-new`](doc/content/whats-new) with the corresponding CHANGELOG from [TheThingsIndustries/lorawan-stack](https://github.com/TheThingsIndustries/lorawan-stack). The title is the release version and the date is the release date.
- [x] The documentation version is up to date.
- [x] The TTI and TTN API documentation has been generated and updated in [doc/data/api](https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/doc/data/api). This includes the following files:

```
doc/data/api/tti.lorawan.v3/messages.yml
doc/data/api/tti.lorawan.v3/services.yml
doc/data/api/tti.lorawan.v3/enums.yml
doc/data/api/ttn.lorawan.v3/messages.yml
doc/data/api/ttn.lorawan.v3/services.yml
doc/data/api/ttn.lorawan.v3/enums.yml
```

- [x] The TTI CLI documentation has been generated and updated in [doc/data](https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/doc/data). This includes the following file:

```
doc/data/ttn-lw-cli.yml
```

- [ ] All generated documentation matches the version that is being released.

### CODE REVIEW

**Comment by nejraselimovic** [comment]
@johanstokking please approve if this is fine

**Review by KrishnaIyer — COMMENTED** [review]
I don't see any `doc/data/api/tti.lorawan.v3/*.yml`. Aren't there any TTS message updates?

**Comment by nejraselimovic** [comment]
> I don't see any `doc/data/api/tti.lorawan.v3/*.yml`. Aren't there any TTS message updates?



> I don't see any `doc/data/api/tti.lorawan.v3/*.yml`. Aren't there any TTS message updates?

I repeated the process and there is still no changes in `doc/data/api/tti.lorawan.v3/*.yml` files, but I can't say anything about it because I don't really know much about it, I just follow the template

**Comment by KrishnaIyer** [comment]
What command are you running?

**Comment by nejraselimovic** [comment]
> What command are you running?

This is the part of the template that updates those files:

- [x] To generate documentation, create a clone of [TheThingsIndustries/lorawan-stack](https://github.com/TheThingsIndustries/lorawan-stack), and **checkout the git tag of the release**.
- [x] To generate API documentation, run the following from within the clone of [TheThingsIndustries/lorawan-stack](https://github.com/TheThingsIndustries/lorawan-stack): 

```bash
$ tools/bin/mage ttiProto:hugoData
```

- [x] Copy generated files to `lorawan-stack-docs` with the following command:

```bash
$ cp api/ttn.lorawan.v3/*.yml /path/to/lorawan-stack-docs/doc/data/api/ttn.lorawan.v3/
$ cp api/tti.lorawan.v3/*.yml /path/to/lorawan-stack-docs/doc/data/api/tti.lorawan.v3/
```

**Comment by KrishnaIyer** [comment]
> To generate API documentation, run the following from within the clone of TheThingsIndustries/lorawan-stack:
$ tools/bin/mage ttiProto:hugoData

I ran this command and I do have changes in `/api/tti.lorawan.v3/`
```
$ tools/bin/mage ttiProto:hugoData

On branch v3.13
Your branch is up to date with 'tti/v3.13'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	api/tti.lorawan.v3/
	api/ttn.lorawan.v3/

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by nejraselimovic** [comment]
> > To generate API documentation, run the following from within the clone of TheThingsIndustries/lorawan-stack:
> > $ tools/bin/mage ttiProto:hugoData
> 
> I ran this command and I do have changes in `/api/tti.lorawan.v3/`
> 
> ```
> $ tools/bin/mage ttiProto:hugoData
> 
> On branch v3.13
> Your branch is up to date with 'tti/v3.13'.
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 	api/tti.lorawan.v3/
> 	api/ttn.lorawan.v3/
> 
> nothing added to commit but untracked files present (use "git add" to track)
> ```

That's weird, I see the same output as you, but when I copy those files, it doesn't recognize any changes there.

**Review by johanstokking — APPROVED** [review]

**Comment by johanstokking** [comment]
> I ran this command and I do have changes in `/api/tti.lorawan.v3/`

What is the problem?

Those generated files aren't checked in to `lorawan-stack` and should be in `.gitignore`.

**Review by KrishnaIyer — APPROVED** [review]

**Pull request merged**
