### PR TITLE
doc: Redirect download button to TTI deployment page

### PR DESCRIPTION
**Pull request by benolayinka**
#### Summary

Redirects the "Get The Things Stack" button to our beautifully designed deployment options chooser

https://www.thethingsindustries.com/deployment/

Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/440

Info from downloads moved to "What is TTS"

Bildschirmfoto 2021-12-22 um 15 09 35

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Comment by nejraselimovic** [comment]
@benolayinka you sure we want this? This was a pretty nice page if you ask me https://www.thethingsindustries.com/docs/download/. If we redirect to deployment options, I think people might not know which distribution is for them. I'm also confused by coexistence of deployments page and this https://www.thethingsindustries.com/tts-plans/

**Comment by benolayinka** [comment]
Add text from downloads page to https://www.thethingsindustries.com/docs/getting-started/what-is-tts/ to an then redirect

**Comment by benolayinka** [comment]
@nejraselimovic info from downloads moved to What is TTS section. okay to merge?

Bildschirmfoto 2021-12-22 um 15 09 35

**Review by nejraselimovic — APPROVED** [review]
Looks great now!

**Pull request merged**
