### PR TITLE
Docs reorganization

### LINKED ISSUE #46: Docs reorganization umbrella issue
#### Summary

Nejra suggested a great list of docs improvements.

- Create a quick start
- Don't use "Enterprise" in value statements, it's confusing because of the distribution names
- Same with "Open source" 
- Visually align tables in Feature Comparison
- Restructure section order - think application, then gateway, then device
- Create quick start
- Improve distribution marking
- Users and Events both require an application - restructure so these are encountered in correct order
- Console before CLI
- Since we provide example files in installation guide, mark the explanation as optional.
- Note not to change TLS source in example installation files
- Troubleshooting is a living doc
- Migrating devices API chart can be improved - what is "not in documentation?
- Reorganize device section slightly (see presentation)
- Limit height of tall pictures
- Remove "adding integrations" card
- Improve sidebar
- Use collapse for code
- Use a better code viewer like https://cloud.google.com/functions/docs/quickstart#functions-clone-sample-repository-nodejs

#### Can you do this yourself and submit a Pull Request?

Will work on it!

### PR DESCRIPTION
**Pull request by nejraselimovic**
#### Summary
Final docs reorganization to close #46

#### Changes
- Moved AWS IoT to Cloud Integrations
- Moved LoRa Edge data visualization via Ubidots under Ubidots as an example 
- Moved Integrations with MQTT Cliends under MQTT Server
- Changed the order of sections in Getting Started and Devices, because it's not really logical. For example, Troubleshooting Getting Started was somewhere in the middle of left hand menu, instead of at the end of the list. One more example - I want to see Console (how to log in) after Installing The Things Stack, because you simply cannot access the Console if you haven't installed the thing.

#### Checklist
- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`, posted screenshots, verified external links. Test with `HUGO_PARAMS_SEARCH_ENABLED=true` if style changes will affect the search bar.
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [ ] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Comment by nejraselimovic** [comment]
@benolayinka could you please look into tables when you have the time? We should come up with a way to at least manage the width of certain columns.

**Review by adriansmares — APPROVED** [review]
Code owned files LGTM.

**Comment by benolayinka** [comment]
Go ahead and merge this without the table fix, proposing a solution for that in a new pr -> https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/387

**Review by johanstokking — APPROVED** [review]
Great work

**Comment by johanstokking** [comment]
Additional review isn't necessary, please update the branch and ping an admin here to merge.

**Comment by nejraselimovic** [comment]
I did the rebase, so @johanstokking (or @htdvisser) you can merge this now

**Pull request merged**
