### PR TITLE
Make frequency plan ID prominent

### PR DESCRIPTION
**Pull request by benolayinka**
#### Summary

Closes https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/56

#### Changes

Looks like:

Screenshot 2020-11-10 at 14 17 08

#### Notes for Reviewers

@kschiffer if you have a style improvement tip lemme know!

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Run Locally: Verified that the docs build using `make server`
- [ ] New Features Marked: Documentation for new features is marked using the `new-in-version` shortcode, according to the guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Style Guidelines: Documentation obeys style guidelines in [CONTRIBUTING](CONTRIBUTING.md).
- [x] Commits: Commit messages follow guidelines in [CONTRIBUTING](CONTRIBUTING.md), there are no fixup commits left.

### CODE REVIEW

**Review by htdvisser — APPROVED** [review]

**Comment by kschiffer** [comment]
> [**@kschiffer**](https://github.com/kschiffer) if you have a style improvement tip lemme know!

*   Display the FP name as heading (e.g. `<h5>` with adjusted margins) and without the gray background
*   Increase the margin between the FP sections
*   The original order was good
*   Display both the ID and base frequency as inline `<pre />`
*   Bonus points for rendering both in a table so that the values will have the same horizontal position

**Review by kschiffer — CHANGES_REQUESTED** [review]
See my other comment.

**Comment by benolayinka** [comment]
> > [**@kschiffer**](https://github.com/kschiffer) if you have a style improvement tip lemme know!
> 
> * Display the FP name as heading (e.g. `<h5>` with adjusted margins) and without the gray background
> * Increase the margin between the FP sections
> * The original order was good
> * Display both the ID and base frequency as inline `<code />`
> * Bonus points for rendering both in a table so that the values will have the same horizontal position

Like so?

Screenshot 2020-11-11 at 15 36 06

**Review by kschiffer — APPROVED** [review]
I meant to use a specially styled minimal table that would just render the values in the same horizontal position:

ID:                          `EU_863_870`
Base frequency:   `868MHz`

However, your solution is neat too. Let's use this instead. The only thing I would change there is using fixed cell widths so that the table layout is always the same.

**Pull request merged**
